name: TEST
on:
  push:
jobs:
  TEST:
    runs-on: self-hosted
    steps:
      - name: Test Command
        shell: tcsh {0}
        run: |
          echo "GitHub Runner running test stage"
          
          echo "set result = `cat /dev/urandom|tr -cd 'a-f0-9' |head -c 32`\necho \"$result\""> /tmp/sourceme
          chmod +x /tmp/sourceme
          "/tmp/sourceme"

