# This is a basic workflow to help you get started with Actions

name: Hello

# Controls when the workflow will run
on:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  TEST:
  runs-on: ubuntu-latest
  # This workflow contains a single job called "build"
  steps:
    - name: Test Command
    shell: tcsh {0}
    run: |
        echo "GitHub Runner running test stage"
        echo "echo 'Hello World'"> /tmp/sourceme
        cat /tmp/sourceme
        source /tmp/sourceme


